# jcmd
# Autogenerated from man page /usr/share/man/man1/jcmd.1.gz
complete -c jcmd -s f -d 'Reads commands from the specified file'
complete -c jcmd -o 'h
.br
-help' -d 'Prints a help message'
complete -c jcmd -s l -d 'Prints the list of running Java processes identifiers with the main class and…'
complete -c jcmd -s h -d or
complete -c jcmd -o help -d 'option prints the tool\'s help message'

