# jdb
# Autogenerated from man page /usr/share/man/man1/jdb.1.gz
complete -c jdb -o help -d 'br Displays a help message'
complete -c jdb -o sourcepath -d 'br Uses the specified path to search for source files in the specified path'
complete -c jdb -o attach -d 'br Attaches the debugger to a running JVM with the default connection mechani…'
complete -c jdb -o listen -d 'br Waits for a running JVM to connect to the specified address with a standar…'
complete -c jdb -o launch -d 'br Starts the debugged application immediately upon startup of JDB'
complete -c jdb -o listconnectors -d 'br List the connectors available in this JVM'
complete -c jdb -o connect -d 'br Connects to the target JVM with the named connector and listed argument va…'
complete -c jdb -o dbgtrace -d 'br Prints information for debugging the \\f3jdb command'
complete -c jdb -o tclient -d 'br Runs the application in the Java HotSpot VM client'
complete -c jdb -o tserver -d 'br Runs the application in the Java HotSpot VM server'
complete -c jdb -o Joption
complete -c jdb -s v -o 'verbose[:class'
complete -c jdb -o Dname
complete -c jdb -o classpath
complete -c jdb -o Xoption

