# jdeps
# Autogenerated from man page /usr/share/man/man1/jdeps.1.gz
complete -c jdeps -o dotoutput -d 'br Destination directory for DOT file output'
complete -c jdeps -s s -o summary -d 'br Prints dependency summary only'
complete -c jdeps -s v -o verbose -d 'br Prints all class-level dependencies'
complete -c jdeps -o verbose:package -d 'br Prints package-level dependencies excluding dependencies within the same a…'
complete -c jdeps -o verbose:class -d 'br Prints class-level dependencies excluding dependencies within the same arc…'
complete -c jdeps -o cp -o classpath -d 'br Specifies where to find class files.   See also Setting the Class Path'
complete -c jdeps -s p -o package -d 'br Finds dependencies in the specified package'
complete -c jdeps -s e -o regex -d 'br Finds dependencies in packages matching the specified regular expression p…'
complete -c jdeps -o include -d 'br Restricts analysis to classes matching pattern'
complete -c jdeps -o jdkinternals -d 'br Finds class-level dependences in JDK internal APIs'
complete -c jdeps -s P -o profile -d 'br Shows profile or the file containing a package'
complete -c jdeps -o apionly -d 'br Restricts analysis to APIs, for example, dependences from the signature of…'
complete -c jdeps -s R -o recursive -d 'br Recursively traverses all dependencies'
complete -c jdeps -o version -d 'br Prints version information'
complete -c jdeps -s h -s '?' -o help

