# jmap
# Autogenerated from man page /usr/share/man/man1/jmap.1.gz
complete -c jmap -o 'dump:[live' -d 'br Dumps the Java heap in \\f3hprof binary format to \\f3filename'
complete -c jmap -o finalizerinfo -d 'br Prints information about objects that are awaiting finalization'
complete -c jmap -o heap -d 'br Prints a heap summary of the garbage collection used, the head configurati…'
complete -c jmap -o histo -d 'br Prints a histogram of the heap'
complete -c jmap -o clstats -d 'br Prints class loader wise statistics of Java heap'
complete -c jmap -s F -d 'br Force'
complete -c jmap -s h -d 'br Prints a help message'
complete -c jmap -o help -d 'br Prints a help message'
complete -c jmap -o Jflag

