# jps
# Autogenerated from man page /usr/share/man/man1/jps.1.gz
complete -c jps -s q -d 'br Suppresses the output of the class name, JAR file name, and arguments pass…'
complete -c jps -s m -d 'br Displays the arguments passed to the \\f3main method'
complete -c jps -s l -d 'br Displays the full package name for the application\'s \\f3main class or the …'
complete -c jps -s v -d 'br Displays the arguments passed to the JVM'
complete -c jps -s V -d 'br Suppresses the output of the class name, JAR file name, and arguments pass…'
complete -c jps -o Joption

