# jstatd
# Autogenerated from man page /usr/share/man/man1/jstatd.1.gz
complete -c jstatd -o nr -d 'br Does not attempt to create an internal RMI registry within the \\f3jstatd p…'
complete -c jstatd -s p -d 'br The port number where the RMI registry is expected to be found, or when no…'
complete -c jstatd -s n -d 'br Name to which the remote RMI object is bound in the RMI registry'
complete -c jstatd -o Joption

