# serialver
# Autogenerated from man page /usr/share/man/man1/serialver.1.gz
complete -c serialver -o classpath -d 'br Sets the search path for application classes and resources'
complete -c serialver -o show -d 'br Displays a simple user interface'
complete -c serialver -o Joption
complete -c serialver -o 'J-Djava.security.manager' -d 'When necessary, a security policy can be specified with the following option:'
complete -c serialver -o 'J-Djava.security.policy' -d 'SEE ALSO    '

